:PROPERTIES:
:ID:       dotemacs-agenda
:END:
#+title: Emacs Config Agenda
#+filetags: :personal:

* DONE Create setter for jnf/override-org-roam-template

Earlier <2022-01-22 Sat> I added the ~jnf/override-org-roam-template~ variable.
Now I need a way to set and unset that.  I’m imaginging the =$= key with a
completing read.  When the value is ~:all~ set ~jnf/override-org-roam-template~
to ~nil~.

The reason for this is that I have subjects and templates.  A subject has many
templates.  Each template applies one or more tags.

* TODO Create a more dynamic filter function

As of <2022-01-23 Sun> I’m relying on a subject based filter.  This naive
approach can work by convention.

What I would like is a filter function that uses the subject’s templates’s tags
as the list.  If the candidate matches one or more of the tags, keep the
candidate.  Otherwise discard.

* TODO Work on Restructuring Roam

The goal is related to [[id:39F360C9-FDDE-4C7E-9FBB-4CF537655F3C][Note Taking with Org Roam]].  I’m finding that there’s too
many “up front” decision points when capturing notes.

What I want is the ability to make two decisions:

- First, is this a reference or a new idea of my own?
- Second, am I working in an assumptive context?

What do I mean “assumptive context?”  When I’m taking notes for a game, there’s
an assumption that anything I generate or link will be “scoped” to that
context.  In other words, I want my templates to auto-tag themselves.  I want
my “keys” to assume one template.  And I want a way to circumvent the
assumption.

I think to how I was specifically using ~org-roam~ to take notes for my Thel
Sector campaign.  I would just type ~s-i~ and start finding a node to link.
That was super fast and helped build a great “relationship graph”.  But that’s
note the case in what I have now.  And so I don’t use it.

I want to get back to those fast decisions.  Why?  Because when taking notes
for a given “assumptive context”, I want DWIM behavior.

** TODO Research how to auto-tag posts by variable

Explored this.
