#+title: README for Dotemacs
#+AUTHOR: Jeremy Friesen
#+EMAIL: jeremy@jeremyfriesen.com
#+STARTUP: showall
#+OPTIONS: toc:3

This is my Emacs configuration repository.  It pairs with my [[https://github.com/jeremyf/dotzshrc/][dotzshrc
repository]].  The [[https://github.com/jeremyf/dotzshrc/blob/main/install.rb][install.rb]] script of the dotzshrc repository uses this
repository.  For implementation reasons, the =emacs.d= directory contains the
init files that I link into my =$HOME/.emacs.d= directory.

For those curious, I wrote [[https://takeonrules.com/2020/10/18/why-i-chose-emacs-as-my-new-text-editor/][Why I Chose Emacs as My New Text Editor // Take on Rules]].

* The Structure

Below is the top-level directory:

#+BEGIN_EXAMPLE
  > tree -L 1
  .
  ├── README.org
  ├── deprecated-packages
  ├── emacs.d
  ├── lib
  └── snippets

  4 directories, 1 file
#+END_EXAMPLE

The files and directories:

- README.org :: This file.
- emacs.d :: A directory that contains files symlinked into =$HOME/.emacs.d= directory.
- deprecated-packages :: A directory of elisp-files.  I have since moved
  towards a literate configuration style.
- snippets :: A directory of [[https://joaotavora.github.io/yasnippet/][yasnippets]] I’ve created.

* The emacs.d Directory

There are two “primary” files to consider in ~./emacs.d~:

- [[file:emacs.d/configuration.org][configuration.org]] :: This file is where I write my Emacs configuration with a
  [[https://en.wikipedia.org/wiki/Literate_programming][Literate programming]] mindset. (/Note:/ This is a conversion from my past
  structure, but as I make new functions, I try to approach solutions with a
  Literate Programming mindset.)
- [[file:emacs.d/init.el][init.el]] :: The file evaluated when Emacs launches.  Using [[https://orgmode.org/worg/org-contrib/babel/intro.html][Org Babel]], it
  evaluates the configuration.org file.
