#+title: README for Dotemacs
#+AUTHOR: Jeremy Friesen
#+EMAIL: jeremy@jeremyfriesen.com
#+STARTUP: showall
#+OPTIONS: toc:3

This is my Emacs configuration repository.  It pairs with my [[https://github.com/jeremyf/dotzshrc/][dotzshrc repository]].  The [[https://github.com/jeremyf/dotzshrc/blob/main/install.rb][install.rb]] script of the dotzshrc repository uses this repository.  For implementation reasons, the =emacs.d= directory contains the init files that I link into my =$HOME/.emacs.d= directory.

For those curious, I wrote [[https://takeonrules.com/2020/10/18/why-i-chose-emacs-as-my-new-text-editor/][Why I Chose Emacs as My New Text Editor // Take on Rules]].

!!hello!!

%%hello%%

* The Structure

Below is the top-level directory:

#+BEGIN_EXAMPLE
  > tree -L 1
  .
  ├── README.org
  ├── emacs.d
  ├── lib
  ├── random-tables
  └── templates

  3 directories, 2 files
#+END_EXAMPLE

The files and directories:

- README.org :: This file.
- emacs.d :: A directory that contains files symlinked into =$HOME/.emacs.d= directory.
- lib :: Some scripts I’ve written to help with my Emacs configuration.
- random-tables :: Fodder for gaming, really not very well developed.
- templates :: Templates for the [[https://github.com/minad/tempel][Emacs tempel package]].
*
The emacs.d Directory

There are two “primary” files to consider in ~./emacs.d~:

- [[file:emacs.d/init.el][init.el]] :: The file evaluated when Emacs launches.
- early-init.el :: The file evaluated early on when Emacs launches.

* Digging Further into emacs.d

The init.el file requires the various files in my =emacs.d= directory.  As of <2022-11-19 Sat> I shifted from Literate configuration to a Emacs Lisp configuration.  I appreciate being able to jump to the definition and edit directly; something that wasn’t immediately obvious with Literate configuration.

Organizing concepts is an interesting challenge, as packages interact in a multi-dimensional manner.  Each of my =jf-<concept>.el= has a rudimentary commentary.

#+begin_example shell
> tree emacs.d
├── abbrev_defs
├── custom.el
├── early-init.el
├── emacs.d
├── hide-comnt.el
├── init.el
├── jf-blogging.el
├── jf-coding.el
├── jf-communicating.el
├── jf-completing.el
├── jf-denote.el
├── jf-fonts-and-iconography.el
├── jf-formatting.el
├── jf-framing.el
├── jf-gaming.el
├── jf-illuminating.el
├── jf-launching.el
├── jf-menus.el
├── jf-minor-mode-maker.el
├── jf-navigating.el
├── jf-org-mode.el
├── jf-organizing.el
├── jf-project.el
├── jf-quick-help.el
├── jf-reading.el
├── jf-utility.el
├── jf-versioning.el
├── jf-windows.el
└── jf-writing.el
#+end_example
