;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        comment-line
        consult-yank
        crux-move-beginning-of-line
        duplicate-line
        electric-pair-delete-pair
        end-of-buffer
        end-of-visual-line
        fill-paragraph
        git-rebase-squash
        hungry-delete-backward
        hungry-delete-forward
        indent-for-tab-command
        jnf/kill-line-or-region
        jnf/kill-region-or-backward-word
        kill-visual-line
        magit-status
        markdown-cycle
        markdown-outdent-or-delete
        mouse-set-region
        ns-copy-including-secondary
        ns-do-show-character-palette
        org-ctrl-c-minus
        org-cycle
        org-end-of-line
        org-force-self-insert
        org-metaleft
        org-metaright
        org-self-insert-command
        org-todo
        org-yank
        sp-backward-delete-char
        string-inflection-all-cycle
        typopunct-insert-ellipsis-or-middot
        typopunct-insert-mp
        typopunct-insert-quotation-mark
        typopunct-insert-typographical-dashes
        wdired-finish-edit
        wgrep-finish-edit
        whole-line-or-region-comment-dwim-2
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        ivy-occur-click
        ivy-switch-buffer
        rspec-toggle-spec-and-target
        rspec-verify-all
        swiper
        xref-find-apropos
        ))
